version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pga-postgres
    environment:
      POSTGRES_DB: strava_activity
      POSTGRES_USER: pga
      POSTGRES_PASSWORD: pga
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgauser -d pgaactivity"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: